/**
 * AI Image Generation Routes
 * Handles AI-powered creative generation and integration with DAM workflow
 */

const express = require('express');
const router = express.Router();
const path = require('path');
const db = require('../config/database');
const aiService = require('../services/aiService');
const dxService = require('../services/dxService');
const { authenticateToken, requireAuthor } = require('../middleware/auth');
const logger = require('../config/logger');

/**
 * GET /api/ai/providers
 * Get available AI providers and their capabilities
 */
router.get('/providers', authenticateToken, (req, res) => {
  try {
    const providers = aiService.getAvailableProviders();
    res.json(providers);
  } catch (error) {
    logger.error('Error fetching AI providers:', error);
    res.status(500).json({ error: 'Failed to fetch AI providers' });
  }
});

/**
 * POST /api/ai/generate
 * Generate a single AI image
 */
router.post('/generate', authenticateToken, requireAuthor, async (req, res) => {
  try {
    const { prompt, provider, size, style, quality } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    const options = {
      provider: provider || 'openai',
      size: size || '1024x1024',
      style: style || 'vivid',
      quality: quality || 'standard'
    };

    const images = await aiService.generateAndSave(prompt, options);

    // Log generation
    await db.query(`
      INSERT INTO ai_generation_history (prompt, provider, options, result_count, generated_by)
      VALUES ($1, $2, $3, $4, $5)
    `, [prompt, options.provider, JSON.stringify(options), images.length, req.user.id]);

    logger.info(`AI image generated by ${req.user.username}: ${prompt.substring(0, 50)}...`);

    res.json({
      success: true,
      images,
      prompt,
      provider: options.provider
    });
  } catch (error) {
    logger.error('Error generating AI image:', error);
    res.status(500).json({ error: error.message || 'Failed to generate image' });
  }
});

/**
 * POST /api/ai/generate-creative-set
 * Generate multiple creative variations based on a theme
 */
router.post('/generate-creative-set', authenticateToken, requireAuthor, async (req, res) => {
  try {
    const { theme, count = 3, style = 'corporate', provider } = req.body;

    if (!theme) {
      return res.status(400).json({ error: 'Theme is required' });
    }

    const options = {
      count: Math.min(count, 5), // Limit to 5 variations
      style,
      provider: provider || 'openai',
      brand: 'Bharat Petroleum'
    };

    const images = await aiService.generateCreativeSet(theme, options);

    // Log generation
    await db.query(`
      INSERT INTO ai_generation_history (prompt, provider, options, result_count, generated_by)
      VALUES ($1, $2, $3, $4, $5)
    `, [theme, options.provider, JSON.stringify(options), images.length, req.user.id]);

    logger.info(`AI creative set generated by ${req.user.username}: ${theme}`);

    res.json({
      success: true,
      images,
      theme,
      style,
      provider: options.provider
    });
  } catch (error) {
    logger.error('Error generating creative set:', error);
    res.status(500).json({ error: error.message || 'Failed to generate creative set' });
  }
});

/**
 * POST /api/ai/generate-and-stage
 * Generate AI image, upload to HCL DX DAM "Not Approved Assets" collection,
 * and start the approval workflow
 */
router.post('/generate-and-stage', authenticateToken, requireAuthor, async (req, res) => {
  try {
    const { 
      prompt, 
      provider, 
      size, 
      style, 
      quality,
      tags = [],
      metadata = {}
    } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    const options = {
      provider: provider || 'openai',
      size: size || '1024x1024',
      style: style || 'vivid',
      quality: quality || 'standard'
    };

    // Generate image locally
    const images = await aiService.generateAndSave(prompt, options);
    const stagedAssets = [];
    const dxAssets = [];

    // Get user's auth token for DX API calls
    const authToken = req.user.ltpaToken || null;

    // Stage each generated image in local DB and upload to HCL DX DAM
    for (const image of images) {
      // Upload to HCL DX DAM "Not Approved Assets" collection
      let dxUploadResult = null;
      try {
        dxUploadResult = await dxService.uploadToNotApproved(
          image.fullPath,
          image.filename,
          image.mimeType,
          {
            ...metadata,
            aiGenerated: 'true',
            aiProvider: options.provider,
            originalPrompt: prompt,
            revisedPrompt: image.revisedPrompt || '',
            generatedAt: new Date().toISOString(),
            tags: [...tags, 'ai-generated', options.provider].join(',')
          },
          authToken
        );
        dxAssets.push(dxUploadResult);
        logger.info(`AI image uploaded to DX DAM Not Approved Assets: ${image.filename}`);
      } catch (dxError) {
        logger.warn(`Failed to upload to DX DAM (continuing with local staging): ${dxError.message}`);
      }

      // Store in local staging database
      const result = await db.query(`
        INSERT INTO staged_assets (
          filename, original_filename, mime_type, file_size, file_path,
          metadata, tags, status, uploaded_by, dx_asset_id, dx_collection_id
        ) VALUES ($1, $2, $3, $4, $5, $6, $7, 'pending_approval', $8, $9, $10)
        RETURNING *
      `, [
        image.filename,
        `AI Generated - ${prompt.substring(0, 50)}`,
        image.mimeType,
        image.size,
        image.path,
        JSON.stringify({
          ...metadata,
          aiGenerated: true,
          aiProvider: options.provider,
          originalPrompt: prompt,
          revisedPrompt: image.revisedPrompt || null,
          generatedAt: new Date().toISOString(),
          dxCollectionName: 'Not Approved Assets',
          dxAssetId: dxUploadResult?.asset?.id || null,
          dxCollectionId: dxUploadResult?.collection?.id || null
        }),
        [...tags, 'ai-generated', options.provider],
        req.user.id,
        dxUploadResult?.asset?.id || null,
        dxUploadResult?.collection?.id || null
      ]);

      // Record workflow history - asset starts in pending_approval status
      await db.query(`
        INSERT INTO workflow_history (entity_type, entity_id, action, to_status, performed_by, metadata)
        VALUES ('asset', $1, 'ai-generate', 'pending_approval', $2, $3)
      `, [
        result.rows[0].id, 
        req.user.id, 
        JSON.stringify({ 
          prompt, 
          provider: options.provider,
          dxAssetId: dxUploadResult?.asset?.id,
          dxCollectionName: 'Not Approved Assets'
        })
      ]);

      stagedAssets.push({
        ...result.rows[0],
        dxCollection: dxUploadResult?.collectionName || null
      });
    }

    // Log generation history
    await db.query(`
      INSERT INTO ai_generation_history (prompt, provider, options, result_count, generated_by, staged_asset_ids)
      VALUES ($1, $2, $3, $4, $5, $6)
    `, [
      prompt, 
      options.provider, 
      JSON.stringify(options), 
      images.length, 
      req.user.id,
      JSON.stringify(stagedAssets.map(a => a.id))
    ]);

    logger.info(`AI image generated, uploaded to DX DAM, and staged by ${req.user.username}: ${prompt.substring(0, 50)}...`);

    res.json({
      success: true,
      message: 'Image generated and uploaded to "Not Approved Assets" collection. Approval workflow started.',
      assets: stagedAssets,
      dxAssets: dxAssets,
      prompt,
      provider: options.provider,
      workflow: {
        currentStatus: 'pending_approval',
        currentCollection: 'Not Approved Assets',
        nextStep: 'Approve to move to "Approved Assets" collection'
      }
    });
  } catch (error) {
    logger.error('Error generating and staging AI image:', error);
    res.status(500).json({ error: error.message || 'Failed to generate and stage image' });
  }
});

/**
 * GET /api/ai/history
 * Get AI generation history for current user
 */
router.get('/history', authenticateToken, async (req, res) => {
  try {
    const { page = 1, limit = 20 } = req.query;
    const offset = (page - 1) * limit;

    const result = await db.query(`
      SELECT agh.*, u.username, u.display_name
      FROM ai_generation_history agh
      LEFT JOIN users u ON agh.generated_by = u.id
      WHERE agh.generated_by = $1
      ORDER BY agh.created_at DESC
      LIMIT $2 OFFSET $3
    `, [req.user.id, limit, offset]);

    const countResult = await db.query(
      'SELECT COUNT(*) FROM ai_generation_history WHERE generated_by = $1',
      [req.user.id]
    );

    res.json({
      history: result.rows,
      pagination: {
        page: parseInt(page),
        limit: parseInt(limit),
        total: parseInt(countResult.rows[0].count),
        totalPages: Math.ceil(countResult.rows[0].count / limit)
      }
    });
  } catch (error) {
    logger.error('Error fetching AI history:', error);
    res.status(500).json({ error: 'Failed to fetch AI generation history' });
  }
});

/**
 * POST /api/ai/enhance-prompt
 * Enhance a basic prompt for better AI image generation
 */
router.post('/enhance-prompt', authenticateToken, async (req, res) => {
  try {
    const { prompt, style = 'corporate' } = req.body;

    if (!prompt) {
      return res.status(400).json({ error: 'Prompt is required' });
    }

    // Style-specific enhancements
    const styleEnhancements = {
      corporate: 'Professional corporate style, clean modern design, high quality, photorealistic, Bharat Petroleum brand colors (green #006B3F and yellow #FFC72C)',
      marketing: 'Eye-catching marketing material, bold vibrant colors, dynamic composition, commercial quality, brand-focused',
      social: 'Social media optimized, engaging visuals, trendy modern aesthetic, shareable content, high engagement design',
      minimal: 'Minimalist design, clean lines, plenty of white space, elegant simplicity, premium feel',
      energetic: 'High energy dynamic design, motion and movement, fuel and power imagery, bold and impactful'
    };

    const enhancement = styleEnhancements[style] || styleEnhancements.corporate;
    const enhancedPrompt = `${prompt}. ${enhancement}. 8K resolution, professional photography, studio lighting.`;

    res.json({
      original: prompt,
      enhanced: enhancedPrompt,
      style
    });
  } catch (error) {
    logger.error('Error enhancing prompt:', error);
    res.status(500).json({ error: 'Failed to enhance prompt' });
  }
});

module.exports = router;
